# Setup
title:               "today music"
tagline:             "今日聞いた音楽"
description:         'その日に聞いた音楽を紹介します。'
url:                 https://ongaeshi.github.io
baseurl:             "/todaymusic"
paginate:            30
permalink:           pretty
timezone:            Asia/Tokyo

# About/contact
author:
  name:              ongaeshi
  url:               https://ongaeshi.me
  email:             ongaeshi0621@gmail.com

# Twitter card
twitter_username:    ongaeshi

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
