# Setup
title:               "today"
tagline:             "今日触ったもの"
description:         'その日の漫画/音楽/動画/ゲームなどを記録'
url:                 https://today.ongaeshi.me
baseurl:             ""
paginate:            30
permalink:           pretty
timezone:            Asia/Tokyo

# About/contact
author:
  name:              ongaeshi
  url:               https://ongaeshi.me
  email:             ongaeshi0621@gmail.com

# Twitter card
twitter_username:    ongaeshi

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
